### ISSUE TITLE
ghc-9.2.5 Data.Record.Anon.Plugin with ANON causes -Wunused-imports for redundant 'Data.Record.Anon.Simple'

### ISSUE THREAD

**Issue by CrystalSplitter** [well-typed/large-records#129]
Hi!

I'm pretty sure this is a bug in `large-anon`, and I wanted to report it. Unsure if this appears in older GHCs, but I don't see why they also *wouldn't* show this warning. It's likely that the test cases just don't cover a case where `Data.Record.Anon.Simple` isn't actually needed anywhere?

cabal v2-build output:

```
Resolving dependencies...
Build profile: -w ghc-9.2.5 -O1
In order, the following will be built (use -v for more details):
 - minimal-0.1.0.0 (lib) (first run)
Configuring library for minimal-0.1.0.0..
Preprocessing library for minimal-0.1.0.0..
Building library for minimal-0.1.0.0..
[1 of 1] Compiling MyLib            ( src/MyLib.hs )

<no location info>: warning: [-Wunused-imports]
    The qualified import of ‘Data.Record.Anon.Simple’ is redundant
      except perhaps to import instances from ‘Data.Record.Anon.Simple’
    To import instances alone, use: import Data.Record.Anon.Simple()
```
Annoyingly, no location info is provided. I'm going to guess it's inserted via the plugin.

Minimal reproducible case:

src/MyLib.hs
```hs
{-# OPTIONS_GHC -fplugin=Data.Record.Anon.Plugin #-}
module MyLib (someFunc) where

someFunc :: IO ()
someFunc = print $ ANON { x = 0 :: Int }
```

minimal.cabal
```cabal
cabal-version:      2.4
name:               minimal
version:            0.1.0.0

library
    exposed-modules:  MyLib
    build-depends:    base >=4.14
                      , large-anon == 0.1.*
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall

```

**Comment by edsko** [comment]
Not a `large-anon` bug, a `ghc` bug, which is giving this incorrect warning; when the import is removed, the code no longer compiles; with the import there, you get the warning. _Extremely_ annoying; if you find a workaround, do let me know! :)

**Comment by CrystalSplitter** [comment]
Aw shame. That's extremely frustrating. I was hoping it was a simple oversight in the plugin code, but I suppose if you already had a solution, you would have patched it by now!

I am a bit confused how this happens though. `reportUnusedNames` (the GHC.Rename.Names entry point that gives the warning) happens fairly late in the type checking. I would assume the type checking portion of the `Data.Record.Anon.Plugin` would reveal the inferred type to come from `Data.Record.Anon` or `Data.Record.Anon.Simple` somewhere along the line, and it would identify the uses correctly.

Do you have any insight as to why this happens?

**Comment by edsko** [comment]
I haven't, but I also haven't spent a ton of time looking at it.

**Comment by edsko** [comment]
In `large-records` itself I currently have

```
  if impl(ghc >= 9.0.1)
    -- ghc 9 provides warnings about unused imports for the imports added by
    -- the plugin. I'm not yet sure how to deal with this properly. The imports
    -- are necessary (I think...?), both for the generated code and to typecheck
    -- the user's own ANN pragma. For now we just disable the warning.
    ghc-options: -Wno-unused-imports
```

which I will be the first to admit is not a solution at all :pensive:

**Comment by phadej** [comment]
The problem is simple: Plugin adds imports which are not written (nor visible) by user.

But it doesn't need to (add imports). The `RdrName`s (in `LargeAnonNames`) could be [`Exact`](https://hackage.haskell.org/package/ghc-9.4.4/docs/GHC-Types-Name-Reader.html#t:RdrName) and then you won't need to add imports, as far as I remember how GHC works.

At least so I do in `overloaded`: https://github.com/phadej/overloaded/blob/master/src/Overloaded/Plugin/Names.hs#L117-L122

**Comment by edsko** [comment]
Ah, awesome, thanks @phadej ! @CrystalSplitter , want to attempt a PR? :)

**Comment by edsko** [comment]
Ah, thanks @phadej , that makes sense. @CrystalSplitter I don't know if/when I will have time to look at this, but hopefully I will at some point.

**Comment by edsko** [comment]
Going to look at this now.

**Comment by edsko** [comment]
Ugh, this is only easy for names where we _know_ what module they are defined in. I fixed `large-anon`, but `large-records` is a lot more annoying to fix :/

**Comment by CrystalSplitter** [comment]
You said it was easy for `large-anon`, but even so I see all the work you did for `large-anon` in 926fc84a6168cb9d62eaa1a575cbf2f3bd59df47. I spent some days trying to poke it, only to realise that I would need to rework how `fresh` would need a state transformer, and got stuck. It's really appreciated that you're trying to fix this!

Is it not able to be fixed for `large-anon` now because of `large-records`, or could it be merged even with the issues in `large-record`?

**Comment by edsko** [comment]
Don't fret, I will fix it for both :)

**Comment by CrystalSplitter** [comment]
Thank you so much, both for the fix and the prompt response!
