### ISSUE TITLE
Type check is giving error as Not in scope: data constructor 'ANON'

### ISSUE THREAD

**Issue by Chaitanya-nair** [well-typed/large-records#140]
Orginal code:
```
uncons ::
  forall a. [a] -> Maybe (Record ["head" :=: a, "tail" :=: [a]])
uncons = \case
  [] -> Nothing
  a : b -> Just (ANON {head = a, tail = b})
```
DynFlags:
["Data.Record.Anon.Plugin","RecordDotPreprocessor"]
Parsed code:
```
uncons ::
  forall a. [a] -> Maybe (Record ["head" :=: a, "tail" :=: [a]])
uncons
  = \case
        [] -> Nothing
        a : b -> Just (ANON {head = a, tail = b})
```

after this type check is giving error as
Not in scope: data constructor 'ANON'

**Comment by Chaitanya-nair** [comment]
Yes

**Comment by Chaitanya-nair** [comment]
Normal cabal build works, we are building a refracting tool on top of this, in which we use ghc `parseModule` and `typecheckModule` that is giving this error

these are the options
`{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor -fplugin=Data.Record.Anon.Plugin #-}
`

**Comment by edsko** [comment]
Then my guess is that that particular ghc invocation is not actually running the plugin.

**Comment by aravindgopall** [comment]
@edsko Can you help us to understand why would simple cabal build is working fine, whereas using GHC as library and calling parseModule followed by typeModule is not. Verified the Dynflags, imports, ghc-options in .cabal file (`-fplugin=RecordDotPreprocessor`), but was not able to figure out the reason.

**Comment by edsko** [comment]
I don't think this is a `large-anon` issue. It sounds to me like ghc is not running the plugin at all. I don't know the ghc driver well enough to be able tell you off the top of my head where something might be wrong. My advice would be to look at the ghc driver and see what it does.

You could try confirming this theory by replacing  the implementation of `plugin` simply by `undefined`; I think that should cause a ghc panic (when running with `cabal`); if it's not when you call it from your own driver, then I guess you know for sure the plugin is not being run.

**Comment by Chaitanya-nair** [comment]
Even if we make it undefined, its the same issue. Seems the plugin is not being run

**Comment by Chaitanya-nair** [comment]
It worked using `setInteractiveDynFlags`. Thanks @edsko for the inputs

**Comment by Chaitanya-nair** [comment]
It worked by setting flags using `setInteractiveDynFlags`. Thanks @edsko for the inputs

**Comment by edsko** [comment]
Good stuff :)
