### ISSUE TITLE
Generated functions are not exported

### ISSUE THREAD

**Issue by avnik** [well-typed/large-records#19]
If we export a LR type explicitly
```Test.hs
{-# LANGUAGE TemplateHaskell, QuasiQuotes #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Test (A(..)) where
import Data.Record.TH (largeRecord, defaultPureScript)

largeRecord defaultPureScript
  [d| data A = A { a :: Int } deriving Show |]
```

and then import it in another module

```Main.hs
module Main where
import Data.Record.TH
import Test (A(..))

main = print [lr| A{ a = 1 } |]
```

it leading to following error:
```
mini/Main.hs:7:18: error:
    • Can't find interface-file declaration for variable Test._construct_A
        Probable cause: bug in .hi-boot file, or inconsistent .hi file
        Use -ddump-if-trace to get an idea of which file caused the error
    • In the first argument of ‘print’, namely ‘(Test._construct_A 1)’
      In the expression: print (Test._construct_A 1)
      In an equation for ‘main’: main = print (Test._construct_A 1)
  |
7 | main = print [lr| A{ a = 1 } |]
  |                  ^^^^^^^^^^^^^^
```

**Comment by edsko** [comment]
Yeah, this is an annoying problem, but I'm not sure there's much we can do about it, since the `large-records` splice cannot affect the export list :/

**Comment by edsko** [comment]
Hmmm maybe I just thought of a work-around. Let me experiment a bit. I agree that having to include that internally generated function in the export list is rather unpleasant.

**Comment by avnik** [comment]
@edsko probably we can push  unsafeGet/unsafeSet/construct into typeclass. Then `A(..)` will export instances of it.

**Comment by edsko** [comment]
Yeah, I was considering that. Signature of `construct` isn't entirely clear though. But I'llexperiment a bit with this this week.

**Comment by avnik** [comment]
@edsko I have some idea for `construct` -- we can have simple `construct :: a -> b` where a is a tuple and b is LR.

```
class LargeRecord a b | a -> b where
  construct :: a -> b

largeRecord defaultPureScript
  [d| data A = A { a :: Int, b :: String } deriving Show |]

instance LargeRecord (Int, String) A where
  construct (a, b) = _construct_A a b
  ```
   looks like workable prototype. 
   
```
-- main = print [lr| A{ a = 1, b = "b" } |]
main = print ((construct (1 :: Int, "b")) :: A)
```

**Comment by edsko** [comment]
Yeah, except the quasi-quoter will need to curry it. I'm currently in the process of tidying up the naming a bit, in order to come up with a solution to #18 that doesn't depend on partial signatures. Once that is done I'll take a look at this.

**Comment by avnik** [comment]
```
{-# LANGUAGE TemplateHaskell, QuasiQuotes, DataKinds, FlexibleInstances, MultiParamTypeClasses, TypeFamilies, UndecidableInstances, ConstraintKinds, ScopedTypeVariables, FlexibleContexts, FunctionalDependencies,  AllowAmbiguousTypes #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Test (A(..), LargeRecord(..)) where
import Data.Kind
import Data.Record.TH (largeRecord, defaultPureScript)

class LargeRecord arg result | result -> arg  where
  construct :: result

largeRecord defaultPureScript
  [d| data A = A { a :: Int, b :: String } deriving Show |]

instance LargeRecord A (Int -> String -> A) where
  construct = _construct_A
  
-- other module
  main = print @A (construct (1 :: Int) "b")
```

Looks bit better, but I doubt about enabling AllowAmbiguousTypes.

**Comment by avnik** [comment]
Today, I tried to implement Construct class with construct function, but still stucked on emitting
```
@A (construct (1 :: Int) "b")
```
stuff, will continue next day

**Comment by edsko** [comment]
Yes, ambiguous types is not a good idea. But we can probably ask for a proxy, in much the same style as #24. I'll try to implement your suggestion, but not sure when I'll get to it. I _hope_ today or tomorrow.

**Comment by edsko** [comment]
@avnik ah, you have  PR in progress? Ok then I'll wait for you. That said, you'll need to rebase on latest `master`. Mind, ambiguous types is not a great idea, but we can avoid it by asking for a value of the record itself, much like `viewAtType` does in #24. After recent refactoring in the library that should be relatively easy.

**Comment by avnik** [comment]
@edsko  not yet PR, but I can submit a WIP (is class and instance code works, but I unable to write construction emitting)

**Comment by edsko** [comment]
Don't worry, take your time. (Or let me know if you want me to take over.)

**Comment by avnik** [comment]
@edsko https://github.com/well-typed/large-records/pull/25
