### ISSUE TITLE
Use the same public constructor for newtype

### ISSUE THREAD

**Issue by kana-sama** [well-typed/large-records#31]
Is it possible to use the same constructor name for newtype as in original data, and rename it only when pattern-synonym is enabled?

There are a lot of code in our project like this:

```haskell
module X (X(MkX)) where
  data X = MkX { a :: Int }

module Y where
  import X (X(MkX))
```

And there is some effort to handle this.

**Comment by edsko** [comment]
Hmm, I see. I didn't realize this was a requirement. I changed this recently as it simplified some stuff. Let me ponder this.

**Comment by edsko** [comment]
I think this is possible, if we accept that you _either_ use the quasi-quoter _or_ the pattern synonym. But I think that's probably okay?

**Comment by kana-sama** [comment]
Yes, we always use only QQ. As I saw, pattern synonym will generate the same stuff as default ghc record, so there are no point in using it at all, am I wrong?

**Comment by edsko** [comment]
Yes, for current versions of ghc, you are right. I'm hoping that with ghc 9.2 (`NoFieldSelectors`) the quasi-quoter becomes obsolete. That's why I've been trying hard to keep the quasi-quoter stuff separate from the rest of the library. Ok, good, then I'll change this.
